security:
    encoders:
        Symfony\Component\Security\Core\User\User:
            id: security.encoder.blowfish
        BConway\WebsiteBundle\Entity\User:
            id: security.encoder.blowfish

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/*
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:       true
            anonymous:    true

    access_control:
       - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/password-reset, role: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/admin/, role: ROLE_ADMIN }
       - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: /edit$|/delete$|/new$|/profile, role: ROLE_USER }
