<?php

namespace BConway\WebsiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LostPetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LostPetRepository extends EntityRepository
{
}
