// Generated by CoffeeScript 1.6.3
(function() {
  $(document).ready(function() {
    $(".radioset").buttonset();
    $("input[type=\"submit\"], button[type=\"submit\"]").button();
    $("#flash_alert").addClass("ui-state-error").addClass("ui-corner-bottom");
    $(".ui-state-highlight").prepend("<span class=\"ui-icon ui-icon-info\" style=\"float: left; margin-right: 1em;\"></span>");
    $(".ui-state-error").prepend("<span class=\"ui-icon ui-icon-alert\" style=\"float: left; margin-right: 1em;\"></span><strong>Alert:</strong> ");
    $(".ui-state-error, .ui-state-highlight").wrapInner("<div style=\"display: inline-block;\" />");
    return $("#search_dialog").dialog({
      autoOpen: false,
      autoResize: true,
      width: 350,
      modal: true,
      buttons: {
        "Search": function() {
          return $('#search_dialog form').submit();
        },
        "Reset Fields": function() {
          return $('#search_dialog form input').val('');
        },
        Cancel: function() {
          return $(this).dialog("close");
        }
      },
      close: function() {}
    }, $("#search_button").button().click(function() {
      return $("#search_dialog").dialog("open");
    }), $("#reset_search").button(), $("#form_searchStartDate").datepicker({
      defaultDate: "-1w",
      changeMonth: true,
      numberOfMonths: 1,
      onClose: function(selectedDate) {
        return $("#form_searchEndDate").datepicker("option", "minDate", selectedDate);
      }
    }), $("#form_searchEndDate").datepicker({
      changeMonth: true,
      numberOfMonths: 1,
      onClose: function(selectedDate) {
        return $("#form_searchStartDate").datepicker("option", "maxDate", selectedDate);
      }
    }));
  });

  this.getParameter = function(paramName) {
    var i, params, searchString, val;
    searchString = window.location.search.substring(1);
    i = void 0;
    val = void 0;
    params = searchString.split("&");
    i = 0;
    while (i < params.length) {
      val = params[i].split("=");
      if (val[0] === paramName) {
        return unescape(val[1]);
      }
      i++;
    }
    return null;
  };

}).call(this);
